---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alexsuch/angular-cli, tag: "7.2.2" }

inputs:
  - name: source
  - name: npm-cache
    path: /cache

outputs:
  - name: artifact

run:
  path: source/ci/build.sh