---
platform: linux

image_resource:
  type: docker-image
  source: { repository: mhart/alpine-node, tag: "6" }

inputs:
  - name: source
  - name: npm-cache
    path: /cache

outputs:
  - name: artifact

run:
  path: source/ci/build.sh